apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "simplenodeservice-team02-qa"
  title: "simplenodeservice-team02-qa"
  description: "Template for the simplenodeservice owned and operated by team02 in environment qa"
  annotations:
    backstage.io/techdocs-ref: dir:.
    # Not working
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=userinterface'
    'backstage.io/kubernetes-namespace': 'simplenodeservice-team02-qa'
    argocd/app-name: simplenodeservice-team02-qa
  links:
    - url: https://github.com/wilson-dynatrace/enablement-openpipeline-segments-iam.git
      title: Github Repo
      icon: github
    - url: https://upgraded-goldfish-j7546q4r4pj3556x-80.app.github.dev/simplenodeservice-team02-qa
      title: "Browse Application"
      icon: subject
    - title: View in ArgoCD
      icon: catalog
      url: https://upgraded-goldfish-j7546q4r4pj3556x-30100.app.github.dev/applications/argocd/simplenodeservice-team02-qa
    - title: View in Dynatrace
      icon: catalog
      url: https://qtn09942.apps.dynatrace.com
    - url: https://community.dynatrace.com
      title: Dynatrace community
      icon: dashboard
spec:
  type: website
  owner: team02
  lifecycle: qa
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: "team02"
  description: Group for application team team02
spec:
  type: business-unit
  profile:
    displayName: Team 02
    email: team02@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  parent: applications
  children: []
#   members: [jdoe]
